### ISSUE TITLE
"Union step error. Can not open some k-mer database in at least one thread"

### ISSUE THREAD

**Issue by trickovicmatija** [ChnMasterOG/KmerGO2#1]
Hello,
Nice tool! I encountered problem running it on MAGs. It finishes the first step and fails immediately when goes to UNION step with error "Can not open some k-mer database in at least one thread" repeated as many time as I have processes. The final line is "Can not open output files in at least one thread.".

Am I doing anything wrong? Test files run successfully! 
Best,
Matija

**Comment by ChnMasterOG** [comment]
Thanks for using KmerGO2. I didn't test it on MAGs. However, this problem may be caused by the thread IO limit.
Try using the command "unlimit -n 1000000"?

**Comment by ChnMasterOG** [comment]
Can you post the screenshot of the output information of UNION step? I think the contigs will not be generated if threre are errors in UNION step.

**Comment by trickovicmatija** [comment]
<img width="670" alt="Screenshot 2022-06-08 at 17 19 04" src="https://user-images.githubusercontent.com/59850947/172654479-941f7286-89f7-4886-9e47-21ad94d410f0.png">
[kmers-out.log](https://github.com/ChnMasterOG/KmerGO2/files/8863002/kmers-out.log)
I am sending the screenshot of the error message, but also the total output of "all" pipeline.
Thanks!

**Comment by ChnMasterOG** [comment]
OK, I see. I think it's the IO problem because I encountered the same error during KmerGO2 development. The number of IO depends on the number of samples and threads(IO = Nsamples * Nthreads). In general. the default limit is 1024.

**Comment by trickovicmatija** [comment]
Working when I lower the number of processes!
Thanks!
One suggestion. Is it possible that the output files of specific kmers are named as traits in .csv file?
Anyway, thanks again. Guess I will be running it on lower number of processes.

Thanks again!
